In [3]:
import numpy as np

In [2]:
print ('ok its working')


ok its working


In [3]:
import numpy as np

In [4]:
arr=np.array([1,2,3,4,5,6])

In [7]:
print(arr)
print('finally working')

[1 2 3 4 5 6]
finally working


In [5]:
print(arr/2)

[0.5 1.  1.5 2.  2.5 3. ]


In [6]:
print('hello')

hello


In [7]:
fval = [x/2 for x in arr]
print(fval)

[np.float64(0.5), np.float64(1.0), np.float64(1.5), np.float64(2.0), np.float64(2.5), np.float64(3.0)]


In [8]:
type (arr)

numpy.ndarray

In [9]:
import matplotlib.pyplot as plt

ModuleNotFoundError: No module named 'matplotlib'

In [15]:
from sys import getsizeof as size
a = np.array([24, 12, 57])
print(size(size(a)))



28


In [17]:
c=[]
print(size(c))
r=np.array([1,2,3,4])
print(size(r))

56
112


In [26]:
ok = np.arange(1,10,3,dtype=int)
print(ok)

[1 4 7]


In [31]:
ok = np.arange(0.1,10,0.2)
print(ok)

[0.1 0.3 0.5 0.7 0.9 1.1 1.3 1.5 1.7 1.9 2.1 2.3 2.5 2.7 2.9 3.1 3.3 3.5
 3.7 3.9 4.1 4.3 4.5 4.7 4.9 5.1 5.3 5.5 5.7 5.9 6.1 6.3 6.5 6.7 6.9 7.1
 7.3 7.5 7.7 7.9 8.1 8.3 8.5 8.7 8.9 9.1 9.3 9.5 9.7 9.9]


In [35]:
lines=np.linspace(1,10,num=5) 
print(lines)

[ 1.    3.25  5.5   7.75 10.  ]


# 2d array 


In [50]:
twodim = np.array([[1,2,3,4],[8,9,0,2]])
print (np.shape(twodim))

(2, 4)


In [66]:
THRDARR= np.array([[[4,2],[5,5]]])
print (THRDARR.shape)

(1, 2, 2)


In [70]:
A = np.array([
[11, 12, 13, 14, 15],
[21, 22, 23, 24, 25],
[31, 32, 33, 34, 35],
[41, 42, 43, 44, 45],
[51, 52, 53, 54, 55]])
print(A[:2,3:])

[[14 15]
 [24 25]]


# EXERCISES

# 1) Create an arbitrary one dimensional array called "v"
# 2) Create a new array which consists of the odd indices of previously created array "v".
# 3) Create a new array in backwards ordering from v.
# 4) What will be the output of the following code:
# a = np.array([1, 2, 3, 4, 5])
# b = a[1:4]
# b[0] = 200
# print(a[1])

In [71]:
v = np.array ([1,2,3,4,5,6,7,8,9,10])

In [74]:
z= np.array(v[::2])

In [75]:
print (z)

[1 3 5 7 9]


In [77]:
a=np.array(v[::-1])
print(a)

[10  9  8  7  6  5  4  3  2  1]


In [78]:
#4>
arr1=np.array ([1,2,3,4,5])
b=a[1:4]
b[0]=200
print(a[1])

200


In [83]:
m= np.array([[1,2],[3,4]])
l= np.array ([m[:1,::-1],m[1:,::-1]])
print(l)
k=np.array([l[::-1]])
print(k)
j=np.array([m[]])

[[[2 1]]

 [[4 3]]]
[[[[4 3]]

  [[2 1]]]]


# dtype


In [87]:
dt = np.dtype([('density',np.int32)])

In [90]:
x=np.array([1,2,3,4,5,6,8],dtype=dt)
print(repr(x))

array([(1,), (2,), (3,), (4,), (5,), (6,), (8,)],
      dtype=[('density', '<i4')])


In [91]:
print(x['density'])

[1 2 3 4 5 6 8]


In [98]:
dt = np.dtype([('country','S20'),('density','i4'),('area','i4'),('population','i4')])
population_table=np.array([
        (
            'netherland',203,3245,1020405
        ),
       (
            'india',204,3223,1020475
        ),
       (
            'america',203,3245,1420405
        ),
       (
            'westindies',203,3245,1026405
       )
],dtype=dt)

In [105]:
print(population_table['country'])
print(population_table['density'])
print(population_table['area'])
print (population_table['population'])



[b'netherland' b'india' b'america' b'westindies']
[203 204 203 203]
[3245 3223 3245 3245]
[1020405 1020475 1420405 1026405]


In [107]:
ab = np.array([1,2,3,4,'asd'])

In [108]:
print(ab)

['1' '2' '3' '4' 'asd']


In [109]:
np.savetxt("population_table.csv",
population_table,
fmt="%s;%d;%d;%d",
delimiter=";")


In [110]:
x = np.genfromtxt("population_table.csv",
dtype=dt,
delimiter=";")
print(x)

[(b"b'netherland'", 203, 3245, 1020405) (b"b'india'", 204, 3223, 1020475)
 (b"b'america'", 203, 3245, 1420405)
 (b"b'westindies'", 203, 3245, 1026405)]


# EXERCISES:
# Before you go on, you may take time to do some exercises to deepen the understanding of the previously
# learned stuff.
# 1. Exercise:
# Define a structured array with two columns. The first column contains the product ID, which can
# be defined as an int32. The second column shall contain the price for the product. How can you
# print out the column with the product IDs, the first row and the price for the third article of this
# structured array?
# 2. Exercise:
# Figure out a data type definition for time records with entries for hours, minutes and seconds

In [118]:
dt = np.dtype([('id',np.int32),('price',np.int32)])
pric_table = np.array([
        (1,1200),
        (2,2346),
        (3,3245),
        (4,4356),
        (5,1234)
    
],dtype=dt)
print(pric_table['id'])
print(pric_table['price'])

[1 2 3 4 5]
[1200 2346 3245 4356 1234]


In [120]:
np.savetxt(
    "pric_table.csv",
    pric_table,
    fmt='%d;%d;',
    delimiter=";"
    
)

In [122]:
x=np.genfromtxt("pric_table.csv",
dtype=dt,
delimiter=";")
print(x)

[(1, 1200) (2, 2346) (3, 3245) (4, 4356) (5, 1234)]
